### ISSUE TITLE
condition "requesting" is true. returning: err_busy

### ISSUE THREAD

**Issue by hdkhanh462** [trflorian/multiplayer-firebase#1]
Some time, it have issue "_condition "requesting" is true. returning: err_busy_" in func "_load_all_players_"

And this happen:
![image](https://github.com/trflorian/multiplayer-firebase/assets/101619460/3e28fa47-fc50-4ed7-b84a-5cf95ccd7e60)

Normal:
![image](https://github.com/trflorian/multiplayer-firebase/assets/101619460/05e40c37-461e-4566-a56d-f19ba47e6818)

**Comment by trflorian** [comment]
Hi there! 

Did you create your own firebase project or did you use my default one? Because some connections are not closed gracefully and a lot of players remain idle in the DB, this is probably what happened on your screenshot. I have now reset the database and I can't reproduce your issue. I suggest you create your own Firebase project, that way you have full control. Check out this blog post for more information and an updated guide on how to set this up:

https://medium.com/@flip.flo.games/online-multiplayer-in-godot-4-with-firebase-realtime-db-without-addons-part-1-2-458ab8f943a3
